spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:/sample-config-master #https://github.com/sunilsoni/sample-config
# While in development mode, you can configure the config server to pick up configuration files from
# the file system
          
#           uri: file://C:/Apigee/micro-services/Work/sample-config

# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 8888          